apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cf0a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cf0a
    app.kubernetes.io/part-of: cin4s-839-0064-app
  name: devfile-sample-cf0a
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cf0a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cf0a
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0064-tenant/cin4s-839-0064-app/devfile-sample-cf0a@sha256:ee66529b93aa11a06feba5d999eb96f47d6c10fcb748e33263f585293d3704d1
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
